### ISSUE TITLE
totem size

### ISSUE THREAD

**Issue by cpuQ** [lugosieben/utools#23]
super useful mod, i was gonna ask for scrollable zoom features and disabling cinematic camera, but it seems like you are already working on it.
so, what would be cool is if you can add options to customize totem size and stuff.

and in the meantime, idk if you can fix this, but i would like to be able to use other zoom mods while also having utools installed, because any other zoom mod seems to be disabled.

thanks!

**Comment by lugosieben** [comment]
> and in the meantime, idk if you can fix this, but i would like to be able to use other zoom mods while also having utools installed, because any other zoom mod seems to be disabled.

This is probably because of the keybinds. Have you tried unbinding the UTools Zoom Keybind? If that still doesn't work, I'll look into it

**Comment by lugosieben** [comment]
> so, what would be cool is if you can add options to customize totem size and stuff.

Do you mean a small totem in the offhand or a smaller totem pop animation? or both?

**Comment by cpuQ** [comment]
> > and in the meantime, idk if you can fix this, but i would like to be able to use other zoom mods while also having utools installed, because any other zoom mod seems to be disabled.
> 
> This is probably because of the keybinds. Have you tried unbinding the UTools Zoom Keybind? If that still doesn't work, I'll look into it

unbinding also doesnt fix the other mods zoom not working, and ive tried with wizoom and zoomify, both which did not seem to work. 
and the totem size, both offhand and pop animation would be great!

**Comment by lugosieben** [comment]
ok, thanks for telling me, ill try to figure out whats going on there

small totem pop / offhand is already coded and will be added in the next release :)
