### ISSUE TITLE
Other zoom mods not compatible

### ISSUE THREAD

**Issue by lugosieben** [lugosieben/utools#25]
Mentioned by @cpuQ in #23

> and in the meantime, idk if you can fix this, but i would like to be able to use other zoom mods while also having utools installed, because any other zoom mod seems to be disabled.

> unbinding also doesnt fix the other mods zoom not working, and ive tried with wizoom and zoomify, both which did not seem to work.

**Comment by lugosieben** [comment]
@cpuQ Since I can't reproduce this bug i've decided to open a new issue. Can you please upload your log to [pastebin](https://pastebin.com/) and send it here?

For me, I can normally use Zoomify while having the UTools Zoom key unbound... very weird

**Comment by lugosieben** [comment]
Added compatibility switch which toggles the zoom functionality completely. 

Thanks to @Kolpixx for allowing me to test since i couldn't reproduce the problem.

Commit: [b6e8a0f](https://github.com/lugosieben/utools/commit/b6e8a0f086e4682beef640dc03465b4340906548)
Available in release v1.3.1

**Comment by cpuQ** [comment]
hello sorry i have not been onliine in a while. do you still need my logs?
your compatibility toggle fixed the issue tho! i can now use other zoom mods, but you already added scroll zoom functionality so i probably wont need other mods anymore
thank you so much :heart:
