### ISSUE TITLE
Copying screenshots

### ISSUE THREAD

**Issue by MidnightsCrow** [lugosieben/utools#40]
usually breaks things on mac, in my case freezes game, so does another mod i use, please add a toggle to auto copy screenshots

**Comment by lugosieben** [comment]
There is a toggle for copying screenshots, you can find it under `/utools config` and the "Other" tab. When toggling this off, does your game still crash?

**Comment by MidnightsCrow** [comment]
> There is a toggle for copying screenshots, you can find it under `/utools config` and the "Other" tab. When toggling this off, does your game still crash?

no it doesent

**Comment by lugosieben** [comment]
Ok, great! I'll mark this as completed then
